export const cards = [
    {
        id: 0, 
        title: 'The Fool',
        description: 'The beginning of a journey or adventure.', 
        image: '/0.jpg',
    }, 
    {
        id: 1,
        title: 'The Magician',
        description: 'Revolutionarily changing circumstances are coming your way.',
        image: '/1.jpg',
    },
    {
        id: 2,
        title: 'The High Priestess',
        description: 'Your intuition is trying to tell you something.',
        image: '/2.jpg',
    },
    {
        id: 3,
        title: 'The Empress',
        description: 'Your are called to mediate a serious situation with poise and grace.',
        image: '/3.jpg',
    },
    {
        id: 4,
        title: 'The Emperor',
        description: 'Your are called to bring discipline and order to a chaotic situation.',
        image: '/4.jpg',
    },
    {
        id: 5,
        title: 'The Hierophant',
        description: 'Turn to traditional teaching and wisdom for the truth here.',
        image: '/5.jpg',
    },
    {
        id: 6,
        title: 'The Lovers',
        description: 'True love and romance.',
        image: '/6.jpg',
    },
    {
        id: 7,
        title: 'The Chariot',
        description: 'Time to take charge and move forward.',
        image: '/7.jpg',
    },
    {
        id: 8,
        title: 'Strength',
        description: 'Stay strong in your convictions and move forward.',
        image: '/8.jpg',
    },
    {
        id: 9,
        title: 'The Hermit',
        description: 'Time to retreat for some me time and introspection.',
        image: '/9.jpg',
    },
    {
        id: 10,
        title: 'The Wheel of Fortune',
        description: 'Revolutionarily changing circumstances are coming your way.',
        image: '/10.jpg',
    },
    {
        id: 11,
        title: 'Justice',
        description: 'Time to set things right.',
        image: '/11.jpg',
    },
    {
        id: 12,
        title: 'The Hanged Man',
        description: 'You seem stuck at a standstill and cannot move ... wait it out.',
        image: '/12.jpg',
    },
    {
        id: 13,
        title: 'Death',
        description: 'Something big is coming to a final end.',
        image: '/13.jpg',
    },
    {
        id: 14,
        title: 'Temperance',
        description: 'Be careful and moderate, or else.',
        image: '/14.jpg',
    },
    {
        id: 15,
        title: 'The Devil',
        description: 'An addictive temptation threatens to overtake you.  Fight your demons.',
        image: '/15.jpg',
    },
    {
        id: 16,
        title: 'The Tower',
        description: 'Unexpected trouble.',
        image: '/16.jpg',
    },
    {
        id: 17,
        title: 'The Star',
        description: 'Hope, renewal, and abundant grace are coming your way.',
        image: '/17.jpg',
    },
    {
        id: 18,
        title: 'The Moon',
        description: 'Hidden forces are at work.  Trust your intuition.',
        image: '/18.jpg',
    },
    {
        id: 19,
        title: 'The Sun',
        description: 'Wealth, flourishing, and fun are coming your way.',
        image: '/19.jpg',
    },
    {
        id: 20,
        title: 'Judgement',
        description: 'It is time to see things for what they really are.',
        image: '/20.jpg',
    },
    {
        id: 21,
        title: 'The World',
        description: 'A great ending will lead to a wonderful new beginning.',
        image: '/21.jpg',
    }
]